global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs: 
  - job_name: "prometheus" 
    static_configs: 
    - targets: ["localhost:9090"]
  - job_name: "node" 
    static_configs: 
    - targets: ["node-exporter:9100"]
  - job_name: "alertmanager" 
    static_configs: 
    - targets: ["alertmanager:9093"]
  - job_name: "cadvisor" 
    static_configs: 
    - targets: ["cadvisor:8080"]  
  - job_name: "hvhost01" 
    scrape_interval: 5s 
    static_configs: 
    - targets: ["localhost:9182"]

