{
 "title": "Ailen Dashboard",
 "time": { "from": "2023-10-09T08:15:49.559Z", "to": "2023-10-09T08:17:26.917Z" },
 "panels": [
  {
   "title": "Sunlight",
   "type": "state-timeline",
   "gridPos": { "h": 12, "w": 20, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"ailen-observatory\")\r\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"census\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"sunlight\")"
    }
   ]
  },
  {
   "title": "Sector Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 12 },
   "targets": [
    {
     "query": "from(bucket: \"ailen-observatory\")\r\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"census\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")"
    }
   ]
  },
  { "title": "Graph Visualization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Human Count",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 10, "x": 0, "y": 21 },
   "targets": [
    {
     "query": "from(bucket: \"ailen-observatory\")\r\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"census\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"human_count\")"
    }
   ]
  },
  {
   "title": "Ailen Count",
   "type": "timeseries",
   "description": "Count of Aliens observed",
   "gridPos": { "h": 17, "w": 10, "x": 10, "y": 21 },
   "targets": [
    {
     "query": "from(bucket: \"ailen-observatory\")\r\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"census\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ailen_count\")"
    }
   ]
  }
 ]
}