{
 "title": "Alien Dashboard",
 "time": { "from": "now-1m", "to": "now" },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sector Temperature",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"alien-observatory\")\r\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"census\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Sunlight",
   "type": "state-timeline",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "query": "from(bucket: \"alien-observatory\")\r\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"census\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"sunlight\")"
    }
   ]
  },
  {
   "title": "Sunlight",
   "type": "gauge",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"alien-observatory\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"census\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"sunlight\")\r\n  |> aggregateWindow(\r\n        every: 1h,\r\n        fn: (column, tables=<-) => tables |> reduce(\r\n            identity: {true_count: 0.0},\r\n            fn: (r, accumulator) => ({\r\n                true_count:\r\n                    if r._value == true then accumulator.true_count + 1.0\r\n                    else accumulator.true_count + 0.0\r\n            })\r\n        )\r\n    )"
    }
   ]
  },
  { "title": "Graph Visualization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Count of Alien Types",
   "type": "barchart",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "query": "from(bucket: \"alien-observatory\")\r\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"census\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"alien_type\")\r\n  |> duplicate(column: \"_value\", as: \"alien_type\")\r\n  |> group(columns: [\"alien_type\"])\r\n  |> count()\r\n  |> group()"
    }
   ]
  },
  {
   "title": "Human Count",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 55 },
   "targets": [
    {
     "query": "from(bucket: \"alien-observatory\")\r\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"census\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"human_count\")"
    }
   ]
  },
  {
   "title": "Alien Count",
   "type": "timeseries",
   "description": "Count of Aliens observed",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 55 },
   "targets": [
    {
     "query": "from(bucket: \"alien-observatory\")\r\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"census\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"alien_count\")"
    }
   ]
  }
 ]
}